kind: pipeline
type: docker
name: Run command

steps:
- name: Run
  pull: always
  image: esperoj/personal
  when:
    event:
    - custom
  environment:
    MACHINE_NAME: ci
    ENCRYPTION_PASSPHRASE:
      from_secret: ENCRYPTION_PASSPHRASE
  commands:
  - echo $${BUILD_DATE}
  - command time -v entrypoint.sh "$${COMMAND}"

trigger:
  branch:
  - main
  event:
  - custom
