kind: pipeline
type: docker
name: Run command

steps:
- name: Run
  pull: always
  image: esperoj/personal
  when:
    event:
    - custom
  environment:
    MACHINE_NAME: ci
    ENCRYPTION_PASSPHRASE:
      from_secret: ENCRYPTION_PASSPHRASE
  commands:
  - echo $${BUILD_DATE}
  - command time -v ~/bin/entrypoint.sh 'cd $(mktemp -d) ; $${COMMAND}'

trigger:
  branch:
  - main
  event:
  - custom

---

kind: pipeline
type: docker
name: Daily Backup

steps:
- name: Backup
  pull: always
  image: esperoj/personal
  environment:
    MACHINE_NAME: ci
    ENCRYPTION_PASSPHRASE:
      from_secret: ENCRYPTION_PASSPHRASE
  commands:
  - echo $${BUILD_DATE}
  - |
    command time -v ~/bin/entrypoint.sh "
    ssh segfault bash -s <<<'
    source ~/.profile
    backup.sh'"

trigger:
  branch:
  - main
  event:
  - cron
  cron:
    include:
    - daily-backup

---

kind: pipeline
type: docker
name: Benchmark

steps:
- name: Benchmark
  pull: always
  image: esperoj/personal
  environment:
    MACHINE_NAME: ci
    ENCRYPTION_PASSPHRASE:
      from_secret: ENCRYPTION_PASSPHRASE
  commands:
  - echo $${BUILD_DATE}
  - |
    command time -v ~/bin/entrypoint.sh "benchmark.sh"

trigger:
  branch:
  - main
  event:
  - cron
  cron:
    include:
    - benchmark
