kind: pipeline
type: docker
name: Run Command

clone:
  disable: true

trigger:
  event:
    - custom

steps:
  - name: run
    image: codeberg.org/esperoj/dotfiles:base
    pull: always
    environment:
      ENCRYPTION_PASSPHRASE:
        from_secret: encryption_passphrase
    commands:
      - |
        command time -v ~/bin/run-command.sh -h "local"

  - name: notify
    image: codeberg.org/esperoj/dotfiles:base
    pull: never
    environment:
      ENCRYPTION_PASSPHRASE:
        from_secret: encryption_passphrase
    commands:
      - |
        ~/bin/run-command.sh -h local -c '
        notify.sh "Workflow $DRONE_STAGE_NAME of repository $DRONE_REPO has completed with status $DRONE_BUILD_STATUS." \
          "Title: A job has completed" \
          "Actions: view, View Log, $DRONE_SYSTEM_HOST/repos/$DRONE_REPO/builds/$DRONE_BUILD_NUMBER" \
        | jq'
