stages:
  - main

default:
  image:
    name: ghcr.io/esperoj/dotfiles
    entrypoint: [""]
  timeout: 3 hours
  after_script:
    - |
      ~/bin/entrypoint.sh '
      xargs -d "\n" notify.sh <<EOL | jq
      Job `$${CI_JOB_NAME}` of repository `$${CI_PROJECT_NAME}`at $${CI_PROJECT_URL} completed with status $${CI_JOB_STATUS}.
      Title: A job has completed
      Actions: view, View Log, $${CI_JOB_URL}
      EOL'

include:
  - local: .gitlab-ci/dev.yml
    rules:
      - if: $WORKFLOW == "dev"
  - local: .gitlab-ci/run-command.yml
    rules:
      - if: $WORKFLOW == "run-command"
  - local: .gitlab-ci/daily.yml
    rules:
      - if: $WORKFLOW == "daily"

build:
  stage: main
  image: debian:stable
  script:
    - echo completed
  rules:
    - if: $WORKFLOW == "build"
  after_script:
    - echo Done