workflow:
  rules:
    - if: $CI_SERVER_HOST == "framagit.org"
      variables:
        DEFAULT_TAG: Debian
        DEFAULT_IMAGE: codeberg.org/esperoj/dotfiles:main
    - if: $CI_SERVER_HOST == "gitlab.com"
      variables:
        DEFAULT_TAG: saas-linux-medium-amd64
        DEFAULT_IMAGE: esperoj/dotfiles:main

stages:
  - main

default:
  image:
    name: $DEFAULT_IMAGE
    entrypoint: [""]
    pull_policy: "always"
  timeout: 6 hours
  tags:
    - $DEFAULT_TAG
  after_script:
    - |
      ~/bin/run-command.sh -h local -c '
      xargs -d "\n" notify.sh <<EOL | jq
      Job "${CI_JOB_NAME}" of repository ${CI_PROJECT_URL} has completed with status ${CI_JOB_STATUS}.
      Title: A job has completed
      Actions: view, View Log, ${CI_JOB_URL}
      EOL'

include:
  - local: .gitlab-ci/dev.yml
    rules:
      - if: $WORKFLOW == "dev"
  - local: .gitlab-ci/run-command.yml
    rules:
      - if: $WORKFLOW == "run-command"
  - local: .gitlab-ci/daily.yml
    rules:
      - if: $WORKFLOW == "daily"
  - local: .gitlab-ci/update-docker.yml
    rules:
      - if: $WORKFLOW == "update-docker"

publish:
  stage: main
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $WORKFLOW == "publish"
    # - if: $CI_PIPELINE_SOURCE == "push" && $CI_SERVER_HOST == "framagit.org" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo -n "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"${DOCKERHUB_AUTH}\"}}}" >> /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination esperoj/dotfiles:latest
  after_script:
    - echo "Done"
