stages:
  - main

include:
  - local: .gitlab-ci/dev.yml
    rules:
      - if: $WORKFLOW == "dev"
  - local: .gitlab-ci/run-command.yml
    rules:
      - if: $WORKFLOW == "run-command"
  - local: .gitlab-ci/daily.yml
    rules:
      - if: $WORKFLOW == "daily"