default:
  image:
    name: ghcr.io/esperoj/dotfiles
    entrypoint: [""]
  timeout: 3 hours

include:
  - local: .gitlab-ci/dev.yml
    rules:
      - if: $WORKFLOW == "dev"
  - local: .gitlab-ci/run-command.yml
    rules:
      - if: $WORKFLOW == "run-command"
  - local: .gitlab-ci/daily.yml
    rules:
      - if: $WORKFLOW == "daily"
  - local: .gitlab-ci/publish.yml
    rules:
      - if: $WORKFLOW == "publish"
      - if: $CI_PIPELINE_SOURCE == "push" && $CI_SERVER_HOST == "framagit.org" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

notify:
  stage: .post
  timeout: 5 minutes
  when: always
  script:
    - |
      ~/bin/entrypoint.sh '
      xargs -d "\n" notify.sh <<EOL | jq
      Job "${CI_JOB_NAME}" of repository ${CI_PROJECT_URL} has completed with status ${CI_JOB_STATUS}.
      Title: A job has completed
      Actions: view, View Log, ${CI_JOB_URL}
      EOL'