stages:
  - main

dev:
  stage: main
  image:
    name: ghcr.io/esperoj/dotfiles:latest
    entrypoint: ["/bin/bash", "-c"]
  cache:
    key: dev
    paths:
      - .cache/
  rules:
    - if: $WORKFLOW == "dev"
  script:
    - command time -v ~/bin/entrypoint.sh "dev-startup.sh"