[GLOBAL]
pants_version = "2.16.0"
backend_packages = [
  "pants.backend.shell",
  "pants.backend.shell.lint.shfmt",
  "pants.backend.shell.lint.shellcheck",
  "pants.backend.docker",
  "pants.backend.docker.lint.hadolint",
]

[python]
interpreter_constraints = ['CPython>=3.7']

[python-bootstrap]
search_path = ["<ASDF>"]

[shfmt]
args = ["--indent 2", "--simplify"]

[anonymous-telemetry]
enabled = true
repo_id = "e617072c-ac56-45e1-9765-e95a8d500e7d"
