version: '3'
dotenv: ['{{.HOME}}/{{.MACHINE_NAME}}/.env', '{{.HOME}}/.env', '.env']
run: when_changed
includes:
  dotfiles: ./taskfiles/dotfiles.yml

tasks:
  setup:
    cmds:
      - echo hi
  build:
    deps:
      - task: setup
        vars: { ENV: 'dev' }
    cmds:
      - echo build