dev:
  stage: main
  image:
    name: ghcr.io/esperoj/dotfiles
    entrypoint: [""]
  rules:
    - if: $WORKFLOW == "dev"
  before_script:
    - |
      ~/bin/entrypoint.sh 'xargs -d "\n" notify.sh <<<"
      Title: Job `${CI_JOB_NAME}` of repository `${CI_PROJECT_NAME}` has started.
      Actions: view, View Log, ${CI_JOB_URL}" \
      | jq'
  script:
    - ~/bin/entrypoint.sh "dev-startup.sh"
  after_script:
    - |
      ~/bin/entrypoint.sh 'xargs -d "\n" notify.sh <<<"
      Title: Job `${CI_JOB_NAME}` of repository `${CI_PROJECT_NAME}` completed with status ${CI_JOB_STATUS}.
      Actions: view, View Log, ${CI_JOB_URL}" \
      | jq'
