run:
  stage: main
  image:
    name: $DEFAULT_IMAGE
    entrypoint: [""]
    pull_policy: "always"
  rules:
    - if: $WORKFLOW == "update-docker"
  script:
    - ~/bin/run-command.sh -h local -c "chezmoi update"