version: 2.1
parameters:
  workflow:
    type: string
    default: ""

jobs:
  ssh:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - run: sudo apt-get -qqy update

workflows:
  ssh-workflow:
    when:
      or:
        - equal: [ssh, << pipeline.parameters.workflow >> ]
        - equal: [main, << pipeline.git.branch >> ]
    jobs:
      - ssh
