variables:
  - &build_plugin plugins/docker
  - base_conditions: &base_conditions
    - event: push
      evaluate: 'CI_SYSTEM_HOST == "ci.codeberg.org"'
  - base_settings: &base_docker_settings
      repo: codeberg.org/esperoj/dotfiles
      auto_tag: true
      registry: codeberg.org
      username: esperoj
      password:
        from_secret: codeberg_token

when: *base_conditions


steps:
  publish:
    image: *build_plugin
    settings:
      <<: *base_docker_settings
    when: *base_conditions

  notify:
    image: codeberg.org/esperoj/dotfiles
    secrets: [ encryption_passphrase ]
    when:
      - event: push
        status: [ success, failure ]
    commands:
      - |
        ~/bin/run-command.sh -h local -c '
        xargs -d "\n" notify.sh <<EOL | jq
        Workflow "$${CI_WORKFLOW_NAME}" of repository $${CI_REPO_URL} has completed with status $${CI_PIPELINE_STATUS}.
        Title: A job has completed
        Actions: view, View Log, $${CI_SYSTEM_URL}/repos/$${CI_REPO}/pipeline/$${CI_PIPELINE_NUMBER}
        EOL'