variables:
  - &build_plugin plugins/docker
  - base_settings: &base_docker_settings
      repo: codeberg.org/esperoj/dotfiles
      secret: id=env,src=env
      auto_tag: true
      registry: codeberg.org
      username: esperoj
      password:
        from_secret: codeberg_token

steps:
  create-env:
    image: public.ecr.aws/docker/library/buildpack-deps:stable-curl
    secrets: [ encryption_passphrase ]
    commands:
      - bash -c 'echo "ENCRYPTION_PASSPHRASE=$${ENCRYPTION_PASSPHRASE@Q}" > env'
  publish:
    image: *build_plugin
    settings:
      <<: *base_docker_settings
      dry-run: false
      target: final
  notify:
    image: codeberg.org/esperoj/dotfiles
    secrets: [ encryption_passphrase ]
    when:
      - status: [ success, failure ]
    commands:
      - |
        ~/bin/entrypoint.sh 'notify.sh "" \
        "Title: Workflow $${CI_WORKFLOW_NAME} of $${CI_REPO_OWNER}/$${CI_REPO_NAME} completed." \
        "Actions: view, View log, $${CI_PIPELINE_URL}" \
        | jq'

when:
  - event: [push, tag]
    branch: main
