variables:
  - &build_plugin plugins/docker
  - base_settings: &base_docker_settings
      repo: codeberg.org/esperoj/dotfiles
      platforms: linux/amd64
      secret: id=env,src=env
      auto_tag: true

steps:
  create-env:
    image: public.ecr.aws/docker/library/buildpack-deps:stable-curl
    secrets: [ encryption_passphrase ]
    commands:
      - bash -c 'echo "ENCRYPTION_PASSPHRASE=$${ENCRYPTION_PASSPHRASE@Q}" > env'
  test:
    image: *build_plugin
    settings:
      <<: *base_docker_settings
      dry-run: true
      target: test
  publish:
    image: *build_plugin
    settings:
      <<: *base_docker_settings
      compress: true
      dry-run: false
      target: production
      registry: codeberg.org
      username: esperoj
      password:
        from_secret: codeberg_token

when:
  - event: [push, tag]
    branch: main
