when:
  - evaluate: 'CI_PIPELINE_EVENT == "push" && CI_SYSTEM_HOST == "ci.codeberg.org"'

variables:
  - &build_plugin plugins/docker
  - base_settings: &base_docker_settings
      repo: codeberg.org/esperoj/dotfiles
      auto_tag: true
      registry: codeberg.org
      username: esperoj
      password:
        from_secret: codeberg_token

steps:
  publish:
    image: *build_plugin
    settings:
      <<: *base_docker_settings
      dry-run: false
  notify:
    image: codeberg.org/esperoj/dotfiles
    secrets: [ encryption_passphrase ]
    when:
      - status: [ success, failure ]
    commands:
      - |
        ~/bin/entrypoint.sh '
        xargs -d "\n" notify.sh <<EOL | jq
        Workflow "$${CI_WORKFLOW_NAME}" of repository $${CI_REPO_URL} has completed with status $${CI_PIPELINE_STATUS}.
        Title: A job has completed
        Actions: view, View Log, $${CI_SYSTEM_URL}/repos/$${CI_REPO}/pipeline/$${CI_PIPELINE_NUMBER}
        EOL'