when:
  - event: [push, tag]
    branch: main

steps:
  test:
    image: public.ecr.aws/docker/library/buildpack-deps:stable
    pull: true
    environment:
      - MACHINE_NAME=container
    secrets: [ encryption_passphrase ]
    commands:
      - ./bin/setup.sh
      - ./bin/entrypoint.sh "chezmoi update && info.sh"
  publish:
    image: codeberg.org/woodpecker-plugins/docker-buildx
    settings:
      dry-run: false
      platforms: linux/amd64
      auto_tag: true
      repo: codeberg.org/esperoj/dotfiles
      registry: codeberg.org
      username: esperoj
      password:
        from_secret: codeberg_token
      compress: true
