when:
  - event: [push, tag]
    branch: main

steps:
  create-env:
    image: public.ecr.aws/docker/library/buildpack-deps:stable-curl
    secrets: [ encryption_passphrase ]
    commands:
      - bash -c 'echo "ENCRYPTION_PASSPHRASE=$${ENCRYPTION_PASSPHRASE@Q}" > env'
  base:
    image: plugins/docker
    settings:
      repo: codeberg.org/esperoj/dotfiles
      platforms: linux/amd64
      compress: true
      tag: base
      dry-run: true
      secret: id=env,src=env
      pull_image: true
      target: base
      no_cache: true
      purge: false
  test:
    image: plugins/docker
    settings:
      repo: codeberg.org/esperoj/dotfiles
      platforms: linux/amd64
      compress: true
      tag: test
      dry-run: true
      secret: id=env,src=env
      pull_image: false
      target: test
      no_cache: false
      purge: true
  publish:
    image: plugins/docker
    settings:
      repo: codeberg.org/esperoj/dotfiles
      platforms: linux/amd64
      compress: true
      auto_tag: true
      dry-run: false
      pull_image: false
      no_cache: false
      purge: true
      secret: id=env,src=env
      target: production
      registry: codeberg.org
      username: esperoj
      password:
        from_secret: codeberg_token
