skip_clone: true

variables:
  - base_conditions: &base_conditions
    - event: cron
      cron: daily # schedule: 15 22 * * 0,4
    - event: manual
      evaluate: 'WORKFLOW == "daily"'

when: *base_conditions


steps:
  run:
    image: codeberg.org/esperoj/dotfiles:base
    pull: true
    environment:
      ENCRYPTION_PASSPHRASE:
        from_secret: encryption_passphrase
    when: *base_conditions
    commands:
      - |
        ~/bin/run-command.sh -h "local" -c "
        chezmoi update --no-tty --force
        . ~/.profile
        make -f ~/recipes/daily.mk -j"

  notify:
    image: codeberg.org/esperoj/dotfiles:base
    pull: true
    environment:
      ENCRYPTION_PASSPHRASE:
        from_secret: encryption_passphrase
    when:
      - event: [cron, manual]
        status: failure
    commands:
      - |
        ~/bin/run-command.sh -h local -c '
          notify.sh "Workflow $${CI_WORKFLOW_NAME} of repository $${CI_REPO_URL} had completed with status $${CI_PIPELINE_STATUS}." \
            "Title: Workflow daily had failed." \
            "Actions: view, View Log, $${CI_SYSTEM_URL}/repos/$${CI_REPO}/pipeline/$${CI_PIPELINE_NUMBER}" | jq'
