when:
  - event: [ cron, manual ]
    cron: daily-backup

skip_clone: true

steps:
  backup:
    when:
      - evaluate: 'CI_PIPELINE_EVENT == "manual" && WORKFLOW == "daily-backup"'
    image: codeberg.org/esperoj/dotfiles
    pull: true
    environment:
      - MACHINE_NAME=container
    secrets: [ encryption_passphrase ]
    commands:
      - uptime
      - |
        command time -v ~/bin/entrypoint.sh "
        ssh segfault bash -s <<<'
        uptime
        . ~/.profile
        chezmoi update
        . ~/.profile
        daily-backup.sh'"
  notify:
    image: codeberg.org/esperoj/dotfiles
    secrets: [ encryption_passphrase ]
    when:
      - status: failure
    commands:
      - |
        ~/bin/entrypoint.sh 'xargs -d "\n" notify.sh <<<"
        Title: Workflow $${CI_WORKFLOW_NAME} of $${CI_REPO} has failed.
        Actions: view, View Log, $${CI_SYSTEM_URL}/repos/$${CI_REPO}/pipeline/$${CI_PIPELINE_NUMBER}" \
        | jq'
