when:
  - event: cron
    cron: daily-backup
  - evaluate: 'CI_PIPELINE_EVENT == "manual" && WORKFLOW == "daily-backup"'

skip_clone: true

steps:
  backup:
    image: codeberg.org/esperoj/dotfiles
    pull: true
    environment:
      - MACHINE_NAME=container
    secrets: [ encryption_passphrase ]
    commands:
      - uptime
      - |
        command time -v ~/bin/entrypoint.sh "
        ssh segfault bash -s <<<'
        . ~/.profile
        chezmoi update
        . ~/.profile
        backup.sh'"
