when:
  - event: cron
    cron: daily
    # schedule: 0 15 22 * * *
  - evaluate: 'CI_PIPELINE_EVENT == "manual" && WORKFLOW == "daily"'

skip_clone: true

steps:
  run:
    image: ghcr.io/esperoj/dotfiles
    pull: true
    secrets: [ encryption_passphrase ]
    commands:
      - |
        command time -v ~/bin/entrypoint.sh "daily.sh"
  notify:
    image: ghcr.io/esperoj/dotfiles
    secrets: [ encryption_passphrase ]
    when:
      - status: failure
    commands:
      - |
        ~/bin/entrypoint.sh 'xargs -d "\n" notify.sh <<<"
        Title: Workflow $${CI_WORKFLOW_NAME} of $${CI_REPO} has failed.
        Actions: view, View Log, $${CI_SYSTEM_URL}/repos/$${CI_REPO}/pipeline/$${CI_PIPELINE_NUMBER}" \
        | jq'
