variables:
  - conditions: &conditions
      when:
        - evaluate: 'CI_PIPELINE_EVENT == "manual" && WORKFLOW == "run-command"'
when:
  - event: manual

skip_clone: true

steps:
  run:
    <<: *conditions
    image: codeberg.org/esperoj/dotfiles
    pull: true
    secrets: [ encryption_passphrase ]
    commands:
      - command time -v ~/bin/entrypoint.sh "$${COMMAND}"
  notify:
    <<: *conditions
    image: codeberg.org/esperoj/dotfiles
    secrets: [ encryption_passphrase ]
    when:
      - status: [ success, failure ]
    commands:
      - |
        ~/bin/entrypoint.sh 'xargs -d "\n" notify.sh <<<"
        Title: Workflow $${CI_WORKFLOW_NAME} of $${CI_REPO_OWNER}/$${CI_REPO_NAME} completed.
        Actions: view, View, $${CI_PIPELINE_URL}" \
        | jq'
