when:
  - evaluate: 'CI_PIPELINE_EVENT == "manual" && WORKFLOW == "run-command"'

steps:
  run:
    image: codeberg.org/esperoj/dotfiles
    pull: true
    environment:
      - MACHINE_NAME=container
    secrets: [ encryption_passphrase ]
    commands:
      - command time -v ~/bin/entrypoint.sh "$${COMMAND}"
