skip_clone: true

variables:
  - base_conditions: &base_conditions
    - event: manual
      evaluate: 'WORKFLOW == "run-command"'

when: *base_conditions


steps:
  run:
    image: codeberg.org/esperoj/dotfiles:main
    pull: true
    secrets: [ encryption_passphrase ]
    when: *base_conditions
    commands:
      - command time -v ~/bin/run-command.sh -h local

  notify:
    image: codeberg.org/esperoj/dotfiles:base
    pull: true
    secrets: [ encryption_passphrase ]
    when:
      - event: manual
        status: [ success, failure ]
    commands:
      - |
        ~/.local/bin/chezmoi init --apply --force
        . ~/.profile
        notify.sh "" \
          "Workflow $${CI_WORKFLOW_NAME} of repository $${CI_REPO_URL} has completed for command $${COMMAND} with status $${CI_PIPELINE_STATUS}." \
          "Title: A job has completed" \
          "Actions: view, View Log, $${CI_SYSTEM_URL}/repos/$${CI_REPO}/pipeline/$${CI_PIPELINE_NUMBER}" | jq
