name: Backup
run-name: Backup
on:
  workflow_dispatch:
  schedule:
    - cron: '23 0 * * *'

jobs:
  Backup:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
      MACHINE_NAME: ci
    timeout-minutes: 60
    steps:
      -
        name: Backup
        run: |
          backup_commands='
          source ${HOME}/.profile
          backup.sh'
          docker run --env ENCRYPTION_PASSPHRASE --rm esperoj/personal:latest "chezmoi update
          ssh segfault bash -s <<<${backup_commands@Q}"
