name: Backup
run-name: Backup
on:
  workflow_dispatch:
  schedule:
    - cron: '23 0 * * *'

jobs:
  Backup:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container:
      image: esperoj/personal:latest
      env:
        ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
        MACHINE_NAME: ci
    timeout-minutes: 60
    steps:
      -
        name: Backup
        run: |
          . "${HOME}/.asdf/asdf.sh"
          chezmoi init --apply --force
          ssh segfault 'bash -s' <<<'
          source "${HOME}/.profile"
          backup.sh'
