name: Benchmark
run-name: Benchmark
on:
  workflow_dispatch:
  schedule:
  - cron: '15 0 * * 0'
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
    steps:
    -
      name: Benchmark
      run: |
        docker run \
        --env ENCRYPTION_PASSPHRASE \
        --rm ghcr.io/esperoj/dotfiles:latest \
        "benchmark.sh"
