name: Benchmark

run-name: Benchmark

on:
  workflow_dispatch:
    #  schedule:
    #  - cron: '15 0 * * 0'

defaults:
  run:
    shell: bash


jobs:
  Benchmark:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    timeout-minutes: 60
    env:
      ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
    steps:
      - name: Benchmark
        run: |
          docker run \
          --env ENCRYPTION_PASSPHRASE \
          --rm ghcr.io/esperoj/dotfiles:latest \
          'command time -v ~/bin/run-command.sh -h "local" -c "benchmark.sh"'
