name: Build
run-name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'


defaults:
  run:
    shell: bash

jobs:
  build:
    if: github.server_url == 'https://github.com' && github.repository == 'esperoj/dotfiles'
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ${{ vars.default_runner || 'ubuntu-latest' }}
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          username: esperoj
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta (base)
        id: meta-base
        uses: docker/metadata-action@master
        with:
          images: |
            esperoj/dotfiles
            ghcr.io/${{ github.repository }}
          tags: |
            base
            base-${{ github.sha }}

      - name: Build and push base Docker image
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}

      - name: Docker meta (main)
        id: meta-main
        uses: docker/metadata-action@master
        with:
          images: |
            esperoj/dotfiles
            ghcr.io/${{ github.repository }}
          tags: |
            main
            main-${{ github.sha }}

      - name: Build and push main Docker image (depends on base)
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64
          build-args: |
            BASE_IMAGE=${{ github.repository }}:base
            SETUP_NAME=docker_main
          push: true
          tags: ${{ steps.meta-main.outputs.tags }}
          labels: ${{ steps.meta-main.outputs.labels }}

      - name: Docker meta (dev)
        id: meta-dev
        uses: docker/metadata-action@master
        with:
          images: |
            esperoj/dotfiles
            ghcr.io/${{ github.repository }}
          tags: |
            dev
            dev-${{ github.sha }}

      - name: Build and push dev Docker image (depends on main)
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64
          build-args: |
            BASE_IMAGE=${{ github.repository }}:main
            SETUP_NAME=docker_dev
          push: true
          tags: ${{ steps.meta-dev.outputs.tags }}
          labels: ${{ steps.meta-dev.outputs.labels }}

      - name: Send notification
        if: always()
        env:
          NTFY_URL: ${{ secrets.NTFY_URL }}
          MY_UUID: ${{ secrets.MY_UUID }}
        run: |
          ./bin/notify.sh "" \
            "Title: Workflow ${{ github.workflow }} of ${{ github.repositoryUrl }} had completed." \
            "Actions: view, View log, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" | jq
