name: Build
run-name: Build
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  Build:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Create env
      run: echo "ENCRYPTION_PASSPHRASE=${ENCRYPTION_PASSPHRASE@Q}" > env
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Test
      uses: docker/build-push-action@v4
      with:
        tags: esperoj/dotfiles:latest
        context: .
        file: Dockerfile
        platforms: linux/amd64
        secret-files: |
          "env=./env"
        push: false
        target: test
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: esperoj/dotfiles:latest
        platforms: linux/amd64
        file: Dockerfile
        no-cache: false
    -
      name: Send notification
      env:
        NTFY_URL: ${{ secrets.NTFY_URL }}
        MY_UUID: ${{ secrets.MY_UUID }}
      if: ${{ always() }}
      run: |
        ./bin/notify.sh "" \
        "Title: Workflow ${{ github.workflow }} of ${{ github.repository }} completed" \
        "Actions: view, View log, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
        | jq
