name: Build
run-name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'


defaults:
  run:
    shell: bash

jobs:
  build:
    if: github.server_url == 'https://github.com' && github.repository == 'esperoj/dotfiles'
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: blacksmith
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (base)
        id: meta-base
        uses: docker/metadata-action@master
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: base

      - name: Build and push base Docker image
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
 
      - name: Docker meta (main)
        id: meta-main
        uses: docker/metadata-action@master
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: main

      - name: Build and push main Docker image (depends on base)
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ github.repository }}:base
            SETUP_NAME=docker_main
          push: true
          tags: ${{ steps.meta-main.outputs.tags }}
          labels: ${{ steps.meta-main.outputs.labels }}

      - name: Docker meta (dev)
        id: meta-dev
        uses: docker/metadata-action@master
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: dev

      - name: Build and push dev Docker image (depends on main)
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ github.repository }}:main
            SETUP_NAME=docker_dev
          push: true
          tags: ${{ steps.meta-dev.outputs.tags }}
          labels: ${{ steps.meta-dev.outputs.labels }}

      - name: Send notification
        if: always()
        env:
          NTFY_URL: ${{ secrets.NTFY_URL }}
          MY_UUID: ${{ secrets.MY_UUID }}
        run: |
          ./bin/notify.sh "" \
          "Title: Workflow ${{ github.workflow }} of ${{ github.repository }} completed" \
          "Actions: view, View log, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          | jq
