name: Daily Backup
run-name: Daily Backup
on:
  workflow_dispatch:
  #schedule:
  #  - cron: '15 22 * * *'

jobs:
  Backup:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
      MACHINE_NAME: ci
    timeout-minutes: 60
    steps:
    -
      name: Backup
      run: |
        docker run --env ENCRYPTION_PASSPHRASE --rm esperoj/dotfiles:latest '
        chezmoi update
        ssh segfault bash -s <<EOL
        source ~/.profile
        backup.sh
        EOL'
