name: Daily
run-name: Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '15 22 * * *'

defaults:
  run:
    shell: bash


jobs:
  daily:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ${{ vars.default_runner || "ubuntu-latest" }}
    container:
      image: esperoj/dotfiles:main
      env:
        ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
        MY_UUID: ${{ secrets.MY_UUID }}
        PING_UUID: ${{ secrets.PING_UUID }}
    timeout-minutes: 60
    steps:
      - name: Daily
        run: |
          cd /root
          export HOME=/root
          ./bin/run-command.sh -h "local" -c "
            chezmoi update
            . ./.profile
            daily.sh
          "
