name: Daily
run-name: Daily

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '15 22 * * *'

defaults:
  run:
    shell: bash


jobs:
  daily:
    if: github.server_url == 'https://git.gay' && github.repository == 'esperoj/dotfiles'
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ${{ vars.default_runner }}
    container:
      image: esperoj/dotfiles:main
      env:
        ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
    timeout-minutes: 60
    steps:
      - name: Daily
        run: /root/bin/run-command.sh -h "local" -c "daily.sh"
