name: Daily Backup
run-name: Daily Backup
on:
  workflow_dispatch:
  #schedule:
  #  - cron: '15 22 * * *'

jobs:
  Backup:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
    timeout-minutes: 60
    steps:
    -
      name: Backup
      run: |
        docker run \
        --env ENCRYPTION_PASSPHRASE \
        --rm ghcr.io/esperoj/dotfiles:latest \
        'chezmoi update
        ssh segfault bash -s <<EOL
        . ~/.profile
        backup.sh
        EOL'
