name: Daily
run-name: Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '15 22 * * 0,2,4'

defaults:
  run:
    shell: bash


jobs:
  daily:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ${{ vars.default_runner || 'ubuntu-latest' }}
    container:
      image: esperoj/dotfiles:main
      env:
        ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
        MY_UUID: ${{ secrets.MY_UUID }}
        PING_UUID: ${{ secrets.PING_UUID }}
    timeout-minutes: 60
    steps:
      - name: Daily
        run: |
          cd /root
          export HOME=/root
          ~/bin/run-command.sh -h "local" -c "
            chezmoi update
            . ./.profile
            daily.sh
          "

      - name: Send notification
        if: ${{ failure() }}
        run: |
          if [[ "${GITHUB_SERVER_URL}" == "https://github.com" ]]; then
            URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          else
            URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_NUMBER}"
          fi
          cd /root
          export HOME=/root
          . ./.profile
          notify.sh "" \
            "Title: Workflow ${{ github.workflow }} of ${{ github.repositoryUrl }} had failed." \
            "Actions: view, View log, $URL" \
            | jq
