name: Run command
run-name: Run command

permissions:
  actions: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'The runner that will run this'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - blacksmith
          - blacksmith-arm
          - docker
          - ubuntu-latest
          - shipfox-2vcpu-ubuntu-2404
      command:
        description: "Run a command"
        required: true
        type: string

defaults:
  run:
    shell: bash


jobs:
  run:
    runs-on: ${{ vars.default_runner == 'docker' && 'docker' || inputs.runner }}
    container:
      image: esperoj/dotfiles:base
      env:
        ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
        COMMAND: ${{ inputs.command }}
        MY_UUID: ${{ secrets.MY_UUID }}
    timeout-minutes: 360
    steps:

      - name: Run
        run: |
          cd /root
          export HOME=/root
          command time -v "$HOME/bin/run-command.sh" -h local

      - name: Send notification
        if: ${{ always() }}
        run: |
          if [[ "${GITHUB_SERVER_URL}" == "https://github.com" ]]; then
            URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          else
            URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_NUMBER}"
          fi
          cd /root
          export HOME=/root
          source ~/.profile
          notify.sh "${COMMAND}" \
            "Title: Workflow ${{ github.workflow }} of ${{ github.repositoryUrl }} had completed." \
            "Actions: view, View log, $URL" \
            | jq
