name: Run command
run-name: Run command

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'The runner that will run this'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - blacksmith
          - blacksmith-arm
          - docker
      command:
        description: "Run a command"
        required: true
        type: string

defaults:
  run:
    shell: bash


jobs:
  Run:
    runs-on: ${{ inputs.runner }}
    container:
      image: esperoj/dotfiles:dev
      env:
        HOME: /root
        ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
        COMMAND: ${{ inputs.command }}
        MY_UUID: ${{ secrets.MY_UUID }}
    timeout-minutes: 360
    steps:
      - name: Run
        run: /root/bin/run-command.sh -h "local" -c "${COMMAND}"

      - name: Send notification
        if: ${{ always() }}
        run: |
          . ~/.profile && notify.sh "${COMMAND}" \
          "Title: Workflow ${{ github.workflow }} of ${{ github.repository }} completed" \
          "Actions: view, View log, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          | jq
