name: Test
run-name: Test
on:
  workflow_dispatch:
 #   schedule:
 #   - cron: '23 0 * * *'
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened]

jobs:
  Test:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup ssh
        env:
          ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
        run: |
          export PATH="$(pwd)/scripts:$PATH"
          source setup.sh setup_ssh
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> "$GITHUB_ENV"
          echo "SSH_AGENT_PID=${SSH_AGENT_PID}" >> "$GITHUB_ENV"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: false
          push: false
          tags: segfault:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: PACKAGES=ALL
          file: Dockerfile
          load: true
          no-cache: false
          platforms: linux/amd64
          ssh: "default=${{ env.SSH_AUTH_SOCK }}"
      -
        name: Test
        env:
          ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
        run: |
          docker run --env ENCRYPTION_PASSPHRASE --rm segfault:latest "chezmoi update && info.sh"
#      -
#        name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: ${{ env.LATEST_TAG }}

