name: Test
run-name: Test
on:
  workflow_dispatch:
  #  schedule:
  #    - cron: '30 23 * * *'
  push:
    branches:
    - 'main'

jobs:
  Test:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date)" >> $GITHUB_OUTPUT
    -
      name: Checkout
      uses: actions/checkout@v3
        #      -
        #        name: Setup ssh
        #        env:
        #          ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
        #        run: |
        #          export PATH="$(pwd)/scripts:$PATH"
        #          source setup.sh setup_ssh
        #          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> "$GITHUB_ENV"
        #          echo "SSH_AGENT_PID=${SSH_AGENT_PID}" >> "$GITHUB_ENV"
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and export to Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        pull: false
        push: false
        tags: esperoj/personal:latest
          #cache-from: type=registry,ref=esperoj/personal:buildcache
          #cache-to: type=registry,ref=esperoj/personal:buildcache,mode=max
        build-args: |
          PACKAGES="BASE DEV NET BIG"
          BUILD_DATE=${{ steps.date.outputs.date }}
        file: Dockerfile
        load: true
        no-cache: false
        platforms: linux/amd64
          #ssh: "default=${{ env.SSH_AUTH_SOCK }}"
    -
      name: Test
      env:
        ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
      run: |
        docker run --env ENCRYPTION_PASSPHRASE --rm esperoj/personal:latest "chezmoi update && info.sh"
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        pull: true
        push: true
        tags: esperoj/personal:latest
        build-args: |
          PACKAGES="BASE DEV NET BIG"
          BUILD_DATE=${{ steps.date.outputs.date }}
        file: Dockerfile
        load: false
        no-cache: false
        platforms: linux/amd64
          # ssh: "default=${{ env.SSH_AUTH_SOCK }}"
    -
      name: Send notification
      env:
        NTFY_URL: ${{ secrets.NTFY_URL }}
        MY_UUID: ${{ secrets.MY_UUID }}
      if: ${{ always() }}
      run: |
        ./bin/notify.sh "" \
        "Title: Workflow ${{ github.workflow }} of ${{ github.repository }} completed" \
        "Actions: view, View log, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
        | jq
