name: Test
run-name: Test
on:
  workflow_dispatch:
  schedule:
    - cron: '23 0 * * *'
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened]

jobs:
  Test:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup ssh
        env:
          ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
        run: |
          export PATH="$(pwd)/scripts:$PATH"
          source setup.sh setup_ssh
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> "$GITHUB_ENV"
          echo "SSH_AGENT_PID=${SSH_AGENT_PID}" >> "$GITHUB_ENV"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: false
          push: false
          tags: segfault:latest
          cache-from: type=registry,ref=esperoj/personal:latest
          cache-to: type=inline
          build-args: PACKAGES="BASE NET DEV BIG"
          file: Dockerfile
          load: true
          no-cache: false
          platforms: linux/amd64
          ssh: "default=${{ env.SSH_AUTH_SOCK }}"
      -
        name: Test
        env:
          ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
        run: |
          docker run --env ENCRYPTION_PASSPHRASE --rm segfault:latest "chezmoi update && info.sh"
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          push: true
          tags: esperoj/personal:latest
          build-args: PACKAGES="BASE NET DEV BIG"
          file: Dockerfile
          load: false
          no-cache: true
          platforms: linux/amd64
          ssh: "default=${{ env.SSH_AUTH_SOCK }}"
      -
        name: Send notification
        env:
          NTFY_URL: ${{ secrets.NTFY_URL }}
          MY_UUID: ${{ secrets.MY_UUID }}
        if: ${{ always() }}
        run: |
          ./scripts/notify.sh "" \
          "Title: Workflow ${{ github.workflow }} of ${{ github.repository }} completed" \
          "Actions: view, View log, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          | jq
