name: Update Docker
run-name: Update Docker

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash


jobs:
  update:
    runs-on: ${{ vars.default_runner || 'ubuntu-latest' }}
    timeout-minutes: 10
    steps:
      - name: Update
        run: |
          df -hT
          docker system prune --all --force
          df -hT
          docker pull esperoj/dotfiles:base
          docker pull esperoj/dotfiles:main
          docker pull esperoj/dotfiles:dev
          docker image ls